version: '3'
services:
    mysql_a:
        build: ./mysql_docker
        container_name: dbPartA
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: coffeeShopPartA

    node_a:
        build: ./node_docker
        depends_on:
            - mysql_a
        container_name: nodePartA
        ports:
            - '80:8080'
        volumes:
            - .:/usr/src/app
